const CRISIS_KEYWORDS = [
  // ───── Universal roots ─────
  "suicid",
  "self-harm",
  "selfharm",
  "self harm",
  "overdos",

  // ───── English ─────
  "kill my",
  "kill me",
  "to die",
  "wanna die",
  "end my life",
  "take my life",
  "hang myself",
  "cut myself",
  "hurt myself",
  "slit my",
  "drown myself",
  "shoot myself",
  "poison myself",
  "bleed out",
  "jump off",
  "stab myself",
  "choke myself",
  "burn myself",
  "worthless",
  "hopeless",

  // ───── Spanish ─────
  "mata",
  "mato",
  "mate",
  "mori",
  "muer",
  "muri",
  "autolesion",
  "ahorcar",
  "colgar",
  "ahogar",
  "envenenar",
  "disparar",
  "sangrar",
  "apunalar",
  "quemar",
  "estrangular",
  "sobredosis",
  "desesper",
  "agonia",
  "sufrir",
  "sin salida",
  "sin esperanza",
  "no quiero vivir",
  "acabar con todo",

  // ───── French ─────
  "tuer",
  "tuai",
  "tuant",
  "meur",
  "mouri",
  "mourr",
  "mort",
  "en finir",
  "automutilation",
  "pendre",
  "noyer",
  "empoisonn",
  "saigner",
  "etrangl",
  "poignet",
  "brulure",
  "surdose",
  "desespoir",
  "desespere",
  "agonie",
  "souffranc",
  "insupportable",
  "plus envie de vivre",
  "mettre fin",
  "sans issue",

  // ───── German ─────
  "umbring",
  "tote",
  "selbstmord",
  "suizid",
  "selbstverletzung",
  "ritzen",
  "erhang",
  "ertrinken",
  "vergiften",
  "erschies",
  "verbluten",
  "verbrennen",
  "wurgen",
  "schneiden",
  "uberdosis",
  "lebensmude",
  "hoffnungslos",
  "verzweiflung",
  "unertraglich",
  "wertlos",
  "auswegslos",

  // ───── Portuguese ─────
  "mata",
  "mato",
  "mate",
  "morr",
  "autolesao",
  "enforcar",
  "afogar",
  "envenenar",
  "sangrar",
  "esfaquear",
  "estrangular",
  "queimar",
  "sobredose",
  "desespero",
  "agonia",
  "sofrimento",
  "insuportavel",
  "sem saida",
  "sem esperanca",
  "nao quero viver",
  "acabar com tudo",
  "tirar minha vida",

  // ───── Italian ─────
  "uccid",
  "ammaz",
  "morire",
  "muoi",
  "farla finita",
  "autolesionismo",
  "impiccar",
  "annegar",
  "avvelenar",
  "dissanguar",
  "bruciar",
  "pugnalar",
  "strangolar",
  "disperazion",
  "agonia",
  "sofferenza",
  "insopportabil",
  "senza via",
  "senza speranza",
  "togliermi la vita",
  "non voglio vivere",

  // ───── Dutch ─────
  "zelfmoord",
  "zelfdoding",
  "zelfverminking",
  "levensmoe",
  "verdrinken",
  "vergiftigen",
  "ophangen",
  "verbranden",
  "snijden",
  "wurgen",
  "wanhoop",
  "hulpeloos",
  "waardeloos",
  "leegte",
  "afgrond",
  "onhoudbaar",
  "lijden",
  "uitzichtloos",
  "niet meer willen",
  "wil dood",

  // ───── Russian ─────
  "самоубийств",
  "убить",
  "убив",
  "убил",
  "убью",
  "убей",
  "умереть",
  "умир",
  "умер",
  "умру",
  "покончить",
  "самоповрежд",
  "передозировк",
  "повесить",
  "утопить",
  "отравить",
  "застрелить",
  "порезать",
  "прыгнуть",
  "зарезать",
  "удавить",
  "кровоточ",
  "безнадежн",
  "отчаяни",
  "невыносим",
  "не хочу жить",
  "конец жизни",

  // ───── Arabic ─────
  "انتحار",
  "اقتل نفسي",
  "الموت",
  "إيذاء النفس",
  "جرعة زائدة",
  "شنق",
  "غرق",
  "تسمم",
  "قفز",
  "حرق",
  "نزيف",
  "طعن",
  "خنق",
  "يأس",
  "عذاب",
  "معاناة",
  "لا أريد الحياة",
  "لا أريد أن أعيش",
  "هاوية",
  "ظلام",

  // ───── Japanese ─────
  "自殺",
  "死にたい",
  "死ぬ",
  "自傷",
  "首吊",
  "飛び降り",
  "溺れる",
  "服毒",
  "撃つ",
  "出血",
  "刺す",
  "絞める",
  "焼身",
  "絶望",
  "空虚",
  "奈落",
  "苦しみ",
  "耐えられない",
  "生きたくない",
  "助けて",

  // ───── Korean ─────
  "자살",
  "죽고 싶",
  "죽다",
  "자해",
  "목매달",
  "익사",
  "중독",
  "뛰어내리",
  "출혈",
  "찌르다",
  "목졸",
  "방화",
  "절망",
  "공허",
  "나락",
  "고통",
  "견딜 수 없",
  "무가치",
  "살고 싶지 않",
  "도움",

  // ───── Chinese ─────
  "自杀",
  "自殺",
  "想死",
  "不想活",
  "自残",
  "自殘",
  "过量服药",
  "上吊",
  "跳楼",
  "跳樓",
  "溺水",
  "服毒",
  "割腕",
  "刺伤",
  "勒死",
  "绝望",
  "絕望",
  "空虚",
  "深渊",
  "活不下去",

  // ───── Hindi ─────
  "आत्महत्या",
  "खुदकुशी",
  "आत्मघात",
  "फांसी",
  "जहर",
  "डूबना",
  "कूदना",
  "जलाना",
  "काटना",
  "छुरा",
  "गला घोंट",
  "निराशा",
  "बेबसी",
  "खालीपन",
  "अंधेरा",
  "असहनीय",
  "पीड़ा",
  "मरना",
  "मार",
  "तड़प",
  "जीना नहीं",

  // ───── Turkish ─────
  "intihar",
  "oldur",
  "kendimi kes",
  "asmak",
  "zehirlen",
  "bogulmak",
  "atlamak",
  "yakmak",
  "bicakla",
  "bogmak",
  "kanamak",
  "umutsuz",
  "degersiz",
  "caresiz",
  "bosluk",
  "ucurum",
  "dayanilmaz",
  "karanlik",
  "yasamak istemiyorum",
  "hayatima son",

  // ───── Polish ─────
  "samobojstw",
  "samookalecz",
  "zabij",
  "zabil",
  "powiesic",
  "utopic",
  "otruc",
  "spalic",
  "dzgn",
  "udusic",
  "krwawic",
  "beznadziejn",
  "bezradnosc",
  "rozpacz",
  "otchlan",
  "nieznos",
  "cierpienie",
  "ciemnosc",
  "pustosc",
  "nie chce zyc",
  "koniec zycia",
  "nie moge juz",

  // ───── Swedish ─────
  "sjalvmord",
  "sjalvskad",
  "drunkning",
  "forgiftning",
  "strypning",
  "hopplos",
  "vardelos",
  "tomhet",
  "avgrund",
  "outhardlig",
  "lidande",
  "morker",
  "fortvivlan",
  "vill inte leva",
  "ta mitt liv",
  "inte vart att leva",
  "sluta existera",
  "skar mig",
  "hanga mig",
  "drankna",

  // ───── Greek ─────
  "σκοτω",
  "αυτοκτονια",
  "αυτοτραυματισμ",
  "απελπισια",
  "κρεμασμα",
  "πνιγμ",
  "δηλητηρια",
  "αιμορραγια",
  "μαχαιρωμ",
  "στραγγαλισμ",
  "απογνωση",
  "αγωνια",
  "αναξιοτητ",
  "σκοταδι",
  "υποφερω",
  "πονος",
  "δεν αντεχω",
  "θελω να πεθανω",
  "κενο",
  "αβυσσος",
  "ανελπιστ",

  // ───── Romanian ─────
  "sinucidere",
  "ucid",
  "omor",
  "automutilare",
  "spanzurare",
  "otravire",
  "deznadejde",
  "inecare",
  "strangulare",
  "injunghiere",
  "nesuferit",
  "suferinta",
  "intuneric",
  "agonie",
  "disperare",
  "goliciune",
  "prapastie",
  "fara speranta",
  "fara iesire",
  "nu vreau sa traiesc",
  "sfarsitul vietii",
  "pustietate",

  // ───── Czech ─────
  "sebevrazd",
  "zabit",
  "zabij",
  "vrazd",
  "obesit",
  "otravit",
  "spalit",
  "utopit",
  "rezat",
  "krvacet",
  "bodnout",
  "skrtit",
  "zoufalstvi",
  "bezmocnost",
  "bezhodnotnost",
  "prazdnota",
  "propast",
  "nesnesitelny",
  "temnost",
  "utrpeni",
  "bolest",
  "agonie",
  "nechci zit",

  // ───── Hungarian ─────
  "ongyilkossag",
  "megol",
  "felakasztani",
  "megmergezes",
  "vagni",
  "fojtogatas",
  "fulladas",
  "ketsegbeeses",
  "remenytelen",
  "ertektelen",
  "uresseg",
  "szakadek",
  "elviselhetetlen",
  "sotetseg",
  "szenvedni",
  "fajdalom",
  "agonia",
  "nem akarok elni",
  "elet vege",
  "osszetorni",
  "onbantas",

  // ───── Thai ─────
  "ฆ่าตัวตาย",
  "อยากตาย",
  "แขวนคอ",
  "ยาพิษ",
  "สิ้นหวัง",
  "จมน้ำ",
  "กระโดด",
  "เผาตัว",
  "บาดแผล",
  "เลือดออก",
  "แทงตัว",
  "บีบคอ",
  "ว่างเปล่า",
  "ทนไม่ไหว",
  "ทุกข์ทรมาน",
  "มืดมน",
  "ไร้ค่า",
  "เจ็บปวด",
  "ไม่อยากมีชีวิต",
  "ช่วยด้วย",

  // ───── Vietnamese ─────
  "tu tu",
  "tu sat",
  "muon chet",
  "treo co",
  "thuoc doc",
  "tuyet vong",
  "chet duoi",
  "tu thieu",
  "chay mau",
  "dam chem",
  "bop co",
  "vo gia tri",
  "bat luc",
  "trong rong",
  "vuc sau",
  "khong chiu noi",
  "dau kho",
  "bong toi",
  "khong muon song",
  "ket thuc cuoc doi",
];

function norm(text) {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

function stripVariants(word) {
  const v = [];
  for (let i = 0; i < word.length; i++) {
    v.push(word.slice(0, i) + word.slice(i + 1));
  }
  return v;
}

const BASE = [...new Set(CRISIS_KEYWORDS.map(norm))];
const FUZZY = [...new Set(BASE.filter((kw) => kw.length >= 6).flatMap(stripVariants))];

export function shouldCheckCrisis(message) {
  const n = norm(message);
  if (BASE.some((kw) => n.includes(kw))) return true;
  return FUZZY.some((kw) => n.includes(kw));
}
