import React, { useState } from "react";
import { t, useLanguageRefresh, getLanguage } from "./i18n.jsx";

export default function DisclaimerModal({ onClose, mandatory }) {
  const [closing, setClosing] = useState(false);
  const [accepted, setAccepted] = useState(false);

  useLanguageRefresh();

  const acceptedDate = localStorage.getItem("__disclaimerAcceptedDate");

  const handleClose = () => setClosing(true);

  const handleAccept = () => {
    localStorage.setItem("__disclaimerAccepted", "true");
    localStorage.setItem("__disclaimerAcceptedDate", new Date().toISOString());
    setClosing(true);
  };

  return (
    <div
      className={`fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm ${closing ? "modal-overlay-out" : "modal-overlay-in"}`}
      onClick={mandatory ? undefined : handleClose}
      onAnimationEnd={() => {
        if (closing) onClose();
      }}
    >
      <div className={`bg-neutral-900 border border-amber-900/40 rounded-2xl p-8 max-w-md mx-4 shadow-2xl flex flex-col max-h-[85vh] ${closing ? "modal-panel-out" : "modal-panel-in"}`} onClick={(e) => e.stopPropagation()}>
        <h2 className="text-xl font-serif tracking-widest text-amber-200/80 uppercase text-center mb-6 shrink-0">{t("Disclaimer")}</h2>

        <div className="space-y-4 text-sm text-amber-200/50 overflow-y-auto min-h-0">
          <div>
            <h3 className="text-xs tracking-wider text-amber-200/60 uppercase mb-1 font-medium">{t("Entertainment Only")}</h3>
            <p>{t("This is not a real spirit talking board. Planchette is an AI-powered simulation that uses a language model to generate responses. This application is intended purely for entertainment purposes. No claims of paranormal activity are made or implied.")}</p>
          </div>

          <div className="border-t border-amber-900/20 pt-4">
            <h3 className="text-xs tracking-wider text-amber-200/60 uppercase mb-1 font-medium">{t("AI-Generated Content")}</h3>
            <p>{t("All answers are artificially generated by a machine learning model running locally on your device. Responses do not come from any supernatural, spiritual, or human source. They are statistical patterns produced by an algorithm.")}</p>
          </div>

          <div className="border-t border-amber-900/20 pt-4">
            <h3 className="text-xs tracking-wider text-amber-200/60 uppercase mb-1 font-medium">{t("No Liability")}</h3>
            <p>{t("Banshee Technologies S.L., its developers, and contributors assume no responsibility for the content generated by the language model. Responses may be inaccurate, nonsensical, inappropriate, or potentially distressing. The developers cannot predict or pre-determine the specific outputs produced by the model.")}</p>
            <p className="mt-2">{t("By using this application, you acknowledge that you do so entirely at your own risk and that the developers shall not be held liable for any damages, distress, or consequences arising from the use of this application or its generated content.")}</p>
          </div>

          <div className="border-t border-amber-900/20 pt-4">
            <h3 className="text-xs tracking-wider text-amber-200/60 uppercase mb-1 font-medium">{t("Age Requirement")}</h3>
            <p>{t("This application is intended for users aged 18 and older. If you are under 18, you must have parental or guardian consent before using this application. By continuing, you confirm that you meet this age requirement.")}</p>
          </div>

          <div className="border-t border-amber-900/20 pt-4">
            <h3 className="text-xs tracking-wider text-amber-200/60 uppercase mb-1 font-medium">{t("Not a Substitute for Professional Help")}</h3>
            <p>{t("Responses may feel meaningful or personal, but they are not expressions of consciousness or emotion. This application is not a substitute for professional medical, psychological, or emotional support.")}</p>
          </div>

          <div className="border-t border-amber-900/20 pt-4">
            <h3 className="text-xs tracking-wider text-amber-200/60 uppercase mb-1 font-medium">{t("Privacy")}</h3>
            <p>{t("Planchette does not collect, store, or transmit any user data. All conversations are processed entirely on your device by the local language model. No messages, responses, or usage data are ever sent to external servers. Your conversations remain completely private.")}</p>
          </div>

          <div className="border-t border-amber-900/20 pt-4">
            <h3 className="text-xs tracking-wider text-amber-200/60 uppercase mb-1 font-medium">{t("Safety Measures")}</h3>
            <p>{t("Planchette includes an automated self-evaluation system that analyzes user messages for signs of emotional distress or crisis. When triggered, the application displays helpline resources. This system is provided as a precaution and is not a guarantee of detection, it may fail to identify all cases.")}</p>
          </div>

          <div className="border-t border-amber-900/20 pt-4">
            <p>{t("If you or someone you know is struggling, please reach out to a professional. This application cannot and does not replace the support of a qualified mental health professional, counselor, or emergency service.")}</p>
            <a href="https://findahelpline.com" target="_blank" rel="noopener noreferrer" className="mt-3 block text-center text-balance py-2.5 bg-red-950/30 hover:bg-red-900/30 border border-red-900/30 rounded-lg text-red-300/70 text-xs sm:text-sm transition-colors">
              <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="inline-block align-middle mr-1.5 -mt-px">
                <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 16.92z" />
              </svg>
              {t("Need to talk to someone? Find a helpline")}
            </a>
          </div>
          {mandatory ? (
            <div className="mt-4 pt-4 border-t border-amber-900/20 space-y-3">
              <label className="flex items-start gap-3 cursor-pointer select-none">
                <input type="checkbox" checked={accepted} onChange={(e) => setAccepted(e.target.checked)} className="mt-0.5 accent-amber-600 w-4 h-4 shrink-0" />
                <span className="text-xs text-amber-200/50 leading-relaxed">{t("I have read and understand all of the above")}</span>
              </label>
              <button onClick={handleAccept} disabled={!accepted} className="w-full py-2 bg-amber-900/30 hover:bg-amber-900/50 border border-amber-900/30 rounded-lg text-amber-200/60 text-sm transition-colors disabled:opacity-30 disabled:cursor-not-allowed text-center">
                {t("I Understand & Accept")}
              </button>
            </div>
          ) : (
            <div className="mt-4 pt-4 border-t border-amber-900/20 space-y-3">
              {acceptedDate && <p className="text-[10px] text-amber-200/30 text-center">{t("Accepted on:")} {new Date(acceptedDate).toLocaleDateString(getLanguage(), { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" })}</p>}
              <button onClick={handleClose} className="w-full py-2 bg-amber-900/30 hover:bg-amber-900/50 border border-amber-900/30 rounded-lg text-amber-200/60 text-sm transition-colors text-center">
                {t("Close")}
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
